// This file is generated by Firebase Extensions.
'use server';
/**
 * @fileOverview A flow to answer frequently asked questions (FAQs) using AI.
 *
 * - answerFAQwithAI - A function that handles answering FAQs using AI.
 * - AnswerFAQwithAIInput - The input type for the answerFAQwithAI function.
 * - AnswerFAQwithAIOutput - The return type for the answerFAQwithAI function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerFAQwithAIInputSchema = z.object({
  question: z.string().describe('The question to be answered.'),
});
export type AnswerFAQwithAIInput = z.infer<typeof AnswerFAQwithAIInputSchema>;

const AnswerFAQwithAIOutputSchema = z.object({
  answer: z.string().describe('The answer to the question.'),
});
export type AnswerFAQwithAIOutput = z.infer<typeof AnswerFAQwithAIOutputSchema>;

export async function answerFAQwithAI(input: AnswerFAQwithAIInput): Promise<AnswerFAQwithAIOutput> {
  return answerFAQwithAIFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerFAQwithAIPrompt',
  input: {schema: AnswerFAQwithAIInputSchema},
  output: {schema: AnswerFAQwithAIOutputSchema},
  prompt: `You are an AI assistant designed to answer frequently asked questions about Vocalweb Solutions.

  Question: {{{question}}}

  Answer:`, // Removed unnecessary instruction about FAQs, refined prompt for direct answer generation.
});

const answerFAQwithAIFlow = ai.defineFlow(
  {
    name: 'answerFAQwithAIFlow',
    inputSchema: AnswerFAQwithAIInputSchema,
    outputSchema: AnswerFAQwithAIOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
